/* =================================================
   CENTRAL DATA SOURCE
================================================= */
export const DATA = {
  objects: [
  "Lantern",
  "Key",
  "Feather",
  "Crystal",
  "Mask",
  "Compass",

  "Hourglass",
  "Ancient Coin",
  "Broken Sword",
  "Glowing Orb",
  "Leather Journal",
  "Sealed Scroll",
  "Wax Candle",
  "Glass Bottle",
  "Magnifying Lens",
  "Pocket Watch",

  "Rusty Locket",
  "Silver Ring",
  "Bronze Shield",
  "Iron Helmet",
  "Ceremonial Dagger",
  "Enchanted Amulet",
  "Runestone",
  "Music Box",
  "Wind Chime",
  "Dream Catcher",

  "Mechanical Gear",
  "Clockwork Key",
  "Steam Valve",
  "Brass Goggles",
  "Pressure Gauge",
  "Copper Pipe",
  "Automaton Hand",
  "Flickering Hologram",
  "Energy Cell",
  "Data Chip",

  "Neural Implant",
  "Worn Backpack",
  "Explorer’s Map",
  "Rope Coil",
  "Grappling Hook",
  "Lockpick Set",
  "Signal Flare",
  "Binoculars",
  "Field Compass",
  "Survival Knife",

  "Crystal Shard",
  "Potion Vial",
  "Herbal Satchel",
  "Phoenix Feather",
  "Dragon Scale",
  "Wizard Hat",
  "Spell Tome",
  "Arcane Focus",
  "Ritual Chalice",
  "Summoning Bell",

  "Ceramic Bowl",
  "Stone Tablet",
  "Carved Idol",
  "Golden Scarab",
  "Hieroglyph Seal",
  "Ivory Comb",
  "Jeweled Crown",
  "Royal Scepter",
  "Embroidered Banner",
  "Ancient Relic",

  "Mirror Shard",
  "Music Flute",
  "Calligraphy Brush",
  "Ink Bottle",
  "Wooden Puppet",
  "Paper Crane",
  "Snow Globe",
  "Star Chart",
  "Astral Compass",
  "Void Fragment"
],

  locations: [
  "Forest",
  "Temple",
  "Castle Gate",
  "Marketplace",
  "Harbor",

  "Ancient Ruins",
  "Hidden Cave",
  "Mountain Pass",
  "Abandoned Village",
  "Underground Catacombs",
  "Desert Oasis",
  "Frozen Tundra",
  "Sunken Shipwreck",
  "Cliffside Path",
  "Sacred Grove",

  "Royal Courtyard",
  "Forgotten Library",
  "Arcane Tower",
  "Sealed Vault",
  "Crystal Cavern",
  "Lava Fields",
  "Ashen Wasteland",
  "Twilight Meadow",
  "Whispering Woods",
  "Haunted Marsh",

  "Clockwork City",
  "Steam Factory",
  "Gearworks District",
  "Inventor’s Workshop",
  "Skybridge",
  "Floating Market",
  "Neon Alley",
  "Cyber Plaza",
  "Data Core",
  "Undercity Slums",

  "Moonlit Beach",
  "Coral Reef",
  "Storm Coast",
  "Fogbound Island",
  "Iceberg Shelf",
  "Hidden Lagoon",
  "Waterfall Basin",
  "River Delta",
  "Mangrove Swamp",
  "Salt Flats",

  "Sacrificial Altar",
  "Sun Temple",
  "Obsidian Pyramid",
  "Burial Chamber",
  "Sandstone Canyon",
  "Caravan Route",
  "Nomad Encampment",
  "Ancient Road",
  "Lost City",
  "Golden Palace",

  "Abandoned Observatory",
  "Starfall Crater",
  "Astral Plane",
  "Void Nexus",
  "Dimensional Rift",
  "Time-Locked Zone",
  "Reality Fracture",
  "Echo Chamber",
  "Memory Archive",
  "Dreamscape",

  "Snowy Hamlet",
  "Icy Fjord",
  "Northern Stronghold",
  "Glacier Cave",
  "Frozen Ruins",
  "Blizzard Plains",
  "Aurora Valley",
  "Ice Fortress",
  "Seal Hunters’ Camp",
  "Polar Outpost",

  "Border Checkpoint",
  "Trade Crossroads",
  "Railway Terminal",
  "Abandoned Station",
  "Old Lighthouse",
  "Smuggler’s Cove",
  "Hidden Passage",
  "Forgotten Tunnel",
  "Collapsed Bridge",
  "Edge of the World"
],

  themes: [
  "Viking",
  "Cyberpunk",
  "Witchcraft",
  "Egyptian",
  "Steampunk",

  "Ancient Greek",
  "Ancient Roman",
  "Norse Mythology",
  "Celtic Mythology",
  "Aztec",
  "Mayan",
  "Incan",
  "Mesopotamian",
  "Persian",
  "Babylonian",

  "Samurai",
  "Feudal Japan",
  "Edo Period",
  "Shinto",
  "Chinese Mythology",
  "Korean Folklore",
  "Mongolian",
  "Silk Road",
  "Himalayan",
  "Tibetan",

  "Medieval Fantasy",
  "High Fantasy",
  "Dark Fantasy",
  "Low Fantasy",
  "Fairy Tale",
  "Grimdark",
  "Arthurian",
  "Elven",
  "Dwarven",
  "Dragon Lore",

  "Solarpunk",
  "Dieselpunk",
  "Atompunk",
  "Biopunk",
  "Post-Apocalyptic",
  "Retro Futurism",
  "Hard Sci-Fi",
  "Space Opera",
  "Interstellar",
  "Alien Civilization",

  "Lovecraftian",
  "Cosmic Horror",
  "Eldritch",
  "Occult",
  "Ritual Magic",
  "Necromancy",
  "Blood Magic",
  "Forbidden Knowledge",
  "Dark Academia",
  "Gothic",

  "Victorian",
  "Edwardian",
  "Industrial Revolution",
  "Belle Époque",
  "Art Nouveau",
  "Art Deco",
  "Jazz Age",
  "Roaring Twenties",
  "Noir",
  "Film Noir",

  "Western",
  "Frontier",
  "Colonial Era",
  "Age of Exploration",
  "Maritime",
  "Pirate",
  "Golden Age of Sail",
  "Nautical Myth",
  "Whaling Era",
  "Harbor Town",

  "Cozy Fantasy",
  "Cottagecore",
  "Dark Cottagecore",
  "Pastoral",
  "Whimsical",
  "Storybook",
  "Children’s Fantasy",
  "Magical Realism",
  "Mythic Realism",
  "Urban Fantasy",

  "Dreamlike",
  "Surreal",
  "Abstract",
  "Psychedelic",
  "Glitchcore",
  "Vaporwave",
  "Weirdcore",
  "Liminal Space",
  "Dreamcore",
  "Trance State",

  // Gothic-focused themes
"Gothic",
"High Gothic",
"Dark Gothic",
"Neo-Gothic",
"Romantic Gothic",

"Victorian Gothic",
"Edwardian Gothic",
"Gaslight Gothic",
"Industrial Gothic",

"Cathedral Gothic",
"Monastic Gothic",
"Abbey Ruins",
"Catacomb Gothic",
"Funereal Gothic",

"Gothic Horror",
"Literary Gothic",
"Southern Gothic",
"Nordic Gothic",
"Urban Gothic",

"Baroque Gothic",
"Rococo Gothic",
"Black Romanticism",
"Decadent Gothic",

"Vampiric",
"Nocturnal",
"Midnight Court",
"Bloodlit Romance",

"Haunted Aristocracy",
"Fallen Nobility",
"Ancient Lineage",
"Rotting Grandeur",

"Dark Chapel",
"Bell Tower Shadows",
"Stained Glass Dreams",
"Raven Court",

"Graveyard Elegy",
"Fogbound Streets",
"Churchyard Mystery",
"Candlelit Catacombs",

"Occult Gothic",
"Ritual Gothic",
"Forbidden Abbey",
"Monastery of Secrets",

"Moonlit Ruins",
"Echoes of the Dead",
"Whispering Corridors",
"Veiled Mourning"
],

  moods: [
  "Serene",
  "Chaotic",
  "Cozy",
  "Mysterious",
  "Energetic",

  "Melancholic",
  "Ethereal",
  "Somber",
  "Tranquil",
  "Haunting",
  "Dreamy",
  "Foreboding",
  "Whimsical",
  "Introspective",
  "Nostalgic",

  "Tense",
  "Brooding",
  "Anxious",
  "Unsettling",
  "Suspenseful",
  "Oppressive",
  "Claustrophobic",
  "Paranoid",
  "Dreadful",
  "Uneasy",

  "Romantic",
  "Bittersweet",
  "Tender",
  "Longing",
  "Yearning",
  "Soft",
  "Warm",
  "Affectionate",
  "Heartfelt",
  "Comforting",

  "Eerie",
  "Sinister",
  "Macabre",
  "Morbid",
  "Creeping",
  "Nocturnal",
  "Shadowy",
  "Funereal",
  "Grim",
  "Bleak",

  "Epic",
  "Heroic",
  "Triumphant",
  "Mythic",
  "Legendary",
  "Grand",
  "Majestic",
  "Awe-Inspiring",
  "Monumental",
  "Cinematic",

  "Playful",
  "Lighthearted",
  "Quirky",
  "Cheerful",
  "Bubbly",
  "Silly",
  "Joyful",
  "Lively",
  "Upbeat",
  "Optimistic",

  "Surreal",
  "Abstract",
  "Hypnotic",
  "Disorienting",
  "Otherworldly",
  "Psychedelic",
  "Hallucinatory",
  "Liminal",
  "Trance-like",
  "Unreal"
],

  artStyles: [
  "Pixel",
  "Watercolor",
  "Oil Paint",
  "Sketch",
  "Low Poly",

  "Charcoal Drawing",
  "Ink Illustration",
  "Line Art",
  "Cross-Hatching",
  "Graphite Drawing",

  "Digital Painting",
  "Concept Art",
  "Matte Painting",
  "Photobashing",
  "Illustrative Realism",

  "Impressionist",
  "Expressionist",
  "Surrealist",
  "Abstract",
  "Cubist",

  "Gothic Illustration",
  "Dark Fantasy",
  "Grimdark",
  "Occult Art",
  "Macabre Illustration",

  "Anime",
  "Manga",
  "Chibi",
  "Visual Novel Style",
  "Cel Shaded",

  "Vaporwave",
  "Synthwave",
  "Cyberpunk Neon",
  "Glitch Art",
  "Datamosh",

  "Minimalist",
  "Flat Design",
  "Geometric",
  "Monoline",
  "Modernist",

  "Fantasy Illustration",
  "High Fantasy",
  "Mythological Art",
  "Epic Fantasy",
  "Storybook Illustration",

  "Art Nouveau",
  "Art Deco",
  "Victorian Illustration",
  "Baroque",
  "Rococo",

  "Collage",
  "Mixed Media",
  "Assemblage",
  "Paper Cutout",
  "Found Object Art",

  "Graffiti",
  "Street Art",
  "Stencil Art",
  "Spray Paint",
  "Urban Illustration",

  "Photorealistic",
  "Hyperrealism",
  "Cinematic Lighting",
  "Dramatic Lighting",
  "Volumetric Lighting",

  "Isometric",
  "Blueprint Style",
  "Technical Illustration",
  "Architectural Rendering",
  "Game Asset Style",

  "Pop Art",
  "Retro Poster",
  "Comic Book Style",
  "Graphic Novel",
  "Screen Print"
],

  seasons: [
  "Spring",
  "Summer",
  "Halloween",
  "Winter",
  "New Year",

  "Early Spring",
  "Late Spring",
  "High Summer",
  "Late Summer",
  "Early Autumn",
  "Mid Autumn",
  "Late Autumn",
  "Early Winter",
  "Mid Winter",
  "Late Winter",

  "Harvest Season",
  "Monsoon Season",
  "Dry Season",
  "Wet Season",
  "Storm Season",
  "Hurricane Season",
  "Blizzard Season",
  "Heatwave",
  "Cold Snap",
  "Frost Season",

  "Autumn Equinox",
  "Spring Equinox",
  "Summer Solstice",
  "Winter Solstice",
  "Day of the Dead",
  "All Souls’ Night",
  "Samhain",
  "Yule",
  "Beltane",
  "Lunar New Year",

  "Valentine’s Day",
  "Easter",
  "Thanksgiving",
  "Christmas Eve",
  "Christmas Morning",
  "Midnight Mass",
  "New Year’s Eve",
  "Festival of Lights",
  "Carnival",
  "Mardi Gras",

  "Golden Hour",
  "Blue Hour",
  "Twilight",
  "Dusk",
  "Dawn",
  "Midnight",
  "Witching Hour",
  "Long Night",
  "Endless Day",
  "Eternal Sunset",

  "Blood Moon",
  "Harvest Moon",
  "Full Moon",
  "New Moon",
  "Lunar Eclipse",
  "Solar Eclipse",
  "Meteor Shower",
  "Stargazing Night",
  "Aurora Season",
  "Comet Passing",

  "Fog Season",
  "Rainy Evening",
  "Snowfall",
  "First Snow",
  "Last Snow",
  "Falling Leaves",
  "Bloom Season",
  "Thaw",
  "Freeze",
  "After the Storm"
],

  people: [
  "Knight",
  "Scientist",
  "Wizard",
  "Villager",
  "Explorer",

  "Alchemist",
  "Necromancer",
  "Summoner",
  "Warlock",
  "Enchantress",
  "Sorcerer",
  "Witch",
  "Rune Keeper",
  "Spellblade",
  "Oracle",

  "Assassin",
  "Mercenary",
  "Bounty Hunter",
  "Rogue",
  "Thief",
  "Smuggler",
  "Pirate",
  "Corsair",
  "Privateer",
  "Outlaw",

  "Monk",
  "Priest",
  "Inquisitor",
  "Cultist",
  "Zealot",
  "Prophet",
  "Heretic",
  "Exorcist",
  "Confessor",
  "Acolyte",

  "King",
  "Queen",
  "Prince",
  "Princess",
  "Duke",
  "Empress",
  "Regent",
  "Noble",
  "Courtier",
  "Diplomat",

  "Blacksmith",
  "Armorer",
  "Cartographer",
  "Scholar",
  "Librarian",
  "Scribe",
  "Engineer",
  "Inventor",
  "Clockmaker",
  "Artificer",

  "Hunter",
  "Tracker",
  "Ranger",
  "Beastmaster",
  "Falconer",
  "Druid",
  "Herbalist",
  "Shaman",
  "Warden",
  "Pathfinder",

  "Detective",
  "Inspector",
  "Archivist",
  "Historian",
  "Anthropologist",
  "Professor",
  "Researcher",
  "Archaeologist",
  "Linguist",
  "Theorist",

  "Android",
  "Cyborg",
  "Clone",
  "AI Entity",
  "Synthetic Being",
  "Time Traveler",
  "Dimension Hopper",
  "Reality Walker",
  "Void Wanderer",
  "Starseer",
  // --- Historical & Cultural Figures ---
  "Renaissance Polymath (Leonardo da Vinci-inspired)",
  "Civil Rights Leader",
  "Freedom Fighter Poet",
  "Philosopher of Reason",
  "Enlightenment Scientist",
  "Pioneering Mathematician",
  "Abolitionist Speaker",
  "Women’s Rights Activist",
  "Labor Movement Organizer",
  "Peace Negotiator",

  // --- Artists & Writers ---
  "Romantic Era Poet",
  "Modernist Novelist",
  "Surrealist Painter",
  "Visionary Playwright",
  "Political Satirist",
  "Beat Generation Writer",
  "Queer Memoirist",
  "Poet of Resistance",
  "Experimental Filmmaker",
  "Counterculture Artist",

  // --- Science & Innovation ---
  "Computing Pioneer",
  "Space Race Engineer",
  "Astrophysicist Communicator",
  "Medical Breakthrough Researcher",
  "Environmental Scientist",
  "Climate Activist Scientist",
  "AI Ethics Researcher",
  "Physics Educator",
  "Biotech Innovator",
  "Accessibility Technology Designer",

  // --- Music & Performance ---
  "Gender-Bending Rock Icon",
  "Soul Music Trailblazer",
  "Jazz Revolutionary",
  "Folk Protest Singer",
  "Disco Era Icon",
  "Electronic Music Pioneer",
  "Queer Pop Superstar",
  "Theatrical Performance Artist",
  "Avant-Garde Composer",
  "Ballroom Scene Legend",

  // --- Film & Acting ---
  "Classic Hollywood Rebel",
  "Method Acting Icon",
  "Indie Film Star",
  "Queer Cinema Pioneer",
  "Genre-Breaking Actor",
  "Sci-Fi Franchise Hero",
  "Award-Winning Character Actor",
  "Experimental Theatre Performer",
  "International Art-House Star",
  "Stage-to-Screen Visionary",

  // --- Activists & Leaders ---
  "LGBTQ+ Rights Activist",
  "Trans Rights Advocate",
  "Intersectional Feminist Leader",
  "Anti-Apartheid Organizer",
  "Humanitarian Organizer",
  "Refugee Rights Advocate",
  "Disability Rights Activist",
  "Youth Climate Organizer",
  "Grassroots Community Builder",
  "Nonviolent Resistance Leader"
]

};