export const horrorPrompts = [
        "A smile that doesn't belong to anyone in the room.",
        "Something whispers your name from inside the walls.",
        "A mirror that reflects a version of you that moves differently.",
        "A house that rearranges itself while you sleep.",
  "A forest where the trees whisper your darkest secrets.",
  "A doll that moves when no one is looking.",
  "A town where everyone disappears at midnight.",
  "A mirror that reflects a version of you you don’t recognize.",
  "A ghost trapped inside a music box.",
  "A child who never ages but grows more sinister each year.",
  "A carnival that only appears in foggy nights.",
  "A painting that bleeds when you touch it.",
  "A graveyard where the dead remember the living.",
  "A book that writes your death as you read it.",
  "A shipwreck haunted by the screams of its crew.",
  "A shadow that follows you even in the light.",
  "A haunted hospital that repairs itself overnight.",
  "A monster that only appears in reflections.",
  "A cursed ring that slowly consumes its wearer’s soul.",
  "A dollmaker whose creations come alive at night.",
  "A staircase that leads to nowhere but whispers your name.",
  "A town where nightmares manifest as reality.",
  "A ghostly train that collects souls instead of passengers.",
  "A forest inhabited by creatures made of mist.",
  "A clock that counts down to a mysterious event.",
  "A cursed photograph that changes each time you look.",
  "A spirit trapped in an old typewriter.",
  "A mansion where every door leads to a different horror.",
  "A mask that forces you to act out its past owner’s crimes.",
  "A child who speaks in the voices of the dead.",
  "A mirror that shows what you fear the most.",
  "A haunted toy store with moving toys at night.",
  "A lighthouse that calls sailors to their doom.",
  "A fog that swallows memories before people vanish.",
  "A vampire who can only walk in daylight.",
  "A painting that predicts future murders.",
  "A cursed forest where travelers never return.",
  "A spirit that mimics your loved ones to trap you.",
  "A carnival ride that traps you in your worst fears.",
  "A town cursed to repeat the same day in horror.",
  "A haunted ship floating in a dry desert.",
  "A figure that appears in every photograph you take.",
  "A clock tower that strikes at the wrong hours.",
  "A house where every mirror shows another world.",
  "A monster that grows stronger when people laugh.",
  "A library filled with forbidden, alive books.",
  "A hotel room that shifts its layout each night.",
  "A doll that whispers secrets about people around you.",
  "A grave that opens and closes on its own.",
  "A creature that eats voices, leaving victims mute.",
  "A cursed playground where children vanish silently.",
  "A mirror maze that traps souls.",
  "A forest where the shadows move independently.",
  "A spirit that follows people into their dreams.",
  "A haunted theater that reenacts tragic events.",
  "A clock that steals time from anyone who touches it.",
  "A cursed artifact that spreads madness.",
  "A room where the walls slowly close in each hour.",
  "A ghostly choir that sings only at midnight.",
  "A haunted mirror that ages whoever looks at it.",
  "A house that remembers every crime ever committed inside.",
  "A shadow that kills when ignored.",
  "A cursed painting that traps viewers inside it.",
  "A vampire who feeds on emotions instead of blood.",
  "A town overrun by invisible creatures.",
  "A spirit that erases itself from memories.",
  "A mask that transforms the wearer into a monster.",
  "A forest that devours anyone who touches its trees.",
  "A dollhouse that controls the real house.",
  "A ship sailing through a sea of shadows.",
  "A cursed journal that writes your darkest thoughts.",
  "A haunted doll that controls the family pets.",
  "A mirror that ages you faster than reality.",
  "A ghost that only appears in photographs.",
  "A mansion that moves to avoid discovery.",
  "A cursed well that shows horrific futures.",
  "A town with streets that shift at night.",
  "A forest that traps travelers in their worst memories.",
  "A creature that mimics your loved ones to lure you.",
  "A haunted attic filled with whispering voices.",
  "A painting that screams when touched.",
  "A ghost that possesses objects instead of people.",
  "A room that traps you in endless darkness.",
  "A shadow that follows and consumes people slowly.",
  "A cursed family heirloom that kills descendants.",
  "A phantom train that collects the lonely.",
  "A haunted mirror that shows your death repeatedly.",
  "A forest that reflects your fears back at you.",
  "A doll that controls your movements at night.",
  "A house that bleeds when broken.",
  "A spirit that replaces your reflection with its own.",
  "A cursed book that whispers secrets of murder.",
  "A ghostly child that repeats the same day forever.",
  "A town where everyone has the same face.",
  "A haunted shipwreck that emerges during storms.",
  "A clock that counts down to your demise.",
  "A mirror that swaps your reflection with something evil.",
  "A haunted music box that plays a death tune.",
  "A shadow that whispers instructions to commit crimes.",
  "A forest where the trees move closer each night.",
  "A spirit that can erase entire memories.",
  "A doll that ages while you remain the same.",
  "A haunted mansion that builds new rooms overnight.",
  "A mask that traps your soul inside.",
  "A ghost that repeats tragic events to anyone who enters.",
  "A cursed lantern that reveals monsters only you can see.",
  "A forest haunted by the echoes of screams.",
  "A mirror that predicts horrible accidents.",
  "A haunted painting that hunts the viewer.",
    ];