/* =============================================
   Prompt Spark — JS System
============================================= */

const promptCard = document.getElementById("prompt-card");
const inspireBtn = document.getElementById("inspire-btn");
const tabs = document.querySelectorAll(".ps-tab");

let currentTheme = "all";

/* =========================
   Prompt Database
========================= */

const prompts = {
    all: [],
    
    general: [
        "A traveler who collects emotions in glass bottles.",
        "A creature made of stitched-together constellations.",
        "A forgotten door in your house that leads somewhere impossible.",
        "Someone who can speak to broken machines.",
    ],

    fantasy: [
        "A wizard who writes spells on floating paper charms.",
        "A forest that only appears when someone is lost.",
        "A knight whose armor is made of living vines.",
        "A mage who bottles starlight to heal others.",
        "A castle that drifts through the clouds like a ship.",
        "A dragon that hoards forgotten childhood memories.",
        "A librarian who guards books that rewrite themselves.",
        "A knight made of broken stained-glass pieces.",
        "A forest where shadows whisper prophecies.",
        "A traveler who speaks the language of storms.",
        "A potion brewer who harvests ingredients from dreams.",
        "A kingdom ruled by a council of enchanted masks.",
        "A fairy who tries to impersonate a human but gets everything slightly wrong.",
        "A river that flows backward to a lost era.",
        "A warrior who befriended the monster they were sent to slay.",
  "A phoenix nurtured by music instead of fire.",
  "A sentient sword that doubts its destiny.",
  "A witch whose familiar keeps trying to run the coven.",
  "A town that celebrates “Opposite Day” using real reality-bending magic.",
  "A royal family descended from sea serpents.",
  "A wandering healer who carries magic in their tattoos.",
  "A centaur scholar building a magical observatory.",
  "A herb garden tended by tiny elemental spirits.",
  "A mountain that shifts its paths to test travelers.",
  "A village protected by a polite but terrifying forest spirit.",
  "A bard whose music forces emotions into physical form.",
  "A ghost knight who guards a ruined bridge.",
  "A relic that grants power but slowly becomes alive.",
  "A dragon disguised as a common house pet.",
  "A kingdom built atop a sleeping giant.",
  "A sorcerer who bargains with the moon.",
  "A shapeshifter trying to live an ordinary life.",
  "A wizard who can only cast spells by writing poems.",
  "A legendary beast that appears only during snowstorms.",
  "A magical bakery that grants wishes through pastries.",
  "A forest where fallen leaves transform into tiny sprites.",
  "A cursed well that shows too many possible futures.",
  "A warrior chosen by a celestial fox.",
  "A haunted harp that plays itself on stormy nights.",
  "A mage academy built inside a colossal shell.",
  "A dragon slayer and dragon forced to team up.",
  "A village where everyone is born with a small magical flaw.",
  "A prophet who only hears omens through animals.",
  "A lantern that contains a fragment of the sun.",
  "A mage trying to resurrect a lost mythical species.",
  "An enchanted book that refuses to open for anyone arrogant.",
  "A giant who collects tiny enchanted trinkets.",
  "An ancient spirit living inside a paintbrush.",
  "A unicorn that refuses to be found.",
  "A guardian spirit trapped in a pocket watch.",
  "A crystal cavern that echoes memories.",
  "A witch who brews potions from forgotten songs.",
  "A stone golem who wants to become human.",
  "A fountain that blesses travelers but takes a memory as payment.",
  "A forest protected by living vines that choose who may pass.",
  "A hero cursed to speak only in riddles.",
  "A merfolk trader dealing in dangerous curiosities.",
  "A dragon egg about to hatch in an unexpected place.",
  "A sentient cloak with a mischievous personality.",
  "A forgotten god awakening after centuries of silence.",
  "A wizard who accidentally turns emotions into weather.",
  "A fairy ring that opens only when no one is looking.",
  "A magical animal companion going on its own adventure.",
  "A warrior who forges weapons from their dreams.",
  "A wandering knight seeking a worthy cause.",
  "A spellworker who steals bad memories.",
  "A city built inside a floating crystal monolith.",
  "A healer who extracts curses like splinters.",
  "A grumpy dragon babysitting magical creatures.",
  "A mage who weaves powerful illusions using glass threads.",
  "A kingdom defended by sentient guardian statues.",
  "A magical storm that erases lies.",
  "A potion that reveals hidden truth — wanted by everyone.",
  "A hermit wizard living inside a giant mushroom.",
  "A knight who rides a phantom horse.",
  "A hidden marketplace that appears only at dawn.",
  "A young mage forced to tame a wild spell.",
  "A creature that repeats everything you say… but wrong.",
  "A fae trickster trying to earn redemption.",
  "A castle that keeps remodeling itself.",
  "A spirit trapped inside a music box.",
  "A cursed tapestry that slowly comes alive.",
  "A witch who commands flowers instead of flames.",
  "A kingdom where everyone has feathers instead of hair.",
  "A river spirit guiding lost travelers.",
  "A legendary sword waiting for its rightful wielder.",
  "A mage who accidentally gave life to their shadow.",
  "A ghost fox haunting an abandoned shrine.",
  "A witch casting spells using embroidered patterns.",
  "A magical pet causing too much trouble.",
  "A knight competing in a mystical tournament.",
  "A world where constellations fall to earth.",
  "A traveler collecting relics from extinct magical species.",
  "A divine messenger disguised as a street performer.",
  "A magical bond forming between strangers.",
  "A hero confronting a benevolent monster.",
  "A corrupted forest yearning to be healed.",
  "A magical creature guarding a forgotten child.",
  "A mage who manipulates time using sand.",
  "A fae creature hiding from its own kind.",
  "A city built atop a slumbering dragon.",
  "A witch who commands wooden puppets.",
  "A young hero guided by a mysterious glowing creature.",
    ],

    scifi: [
        "A robot learning to dream for the first time.",
        "A city powered by bottled thunderstorms.",
        "A spaceship grown like a living organism.",
        "A spaceship that harvests stars for fuel.",
  "An AI that dreams of becoming human.",
  "A planet where time moves backward every other day.",
  "A rogue astronaut communicating with a parallel Earth.",
  "A city floating above a toxic ocean.",
  "A scientist who can transfer consciousness into machines.",
  "A robot detective investigating its own crimes.",
  "A starship that vanishes into other dimensions.",
  "A colony on Mars struggling with mysterious illnesses.",
  "A hologram that starts gaining real memories.",
  "A civilization powered entirely by musical vibrations.",
  "A black hole that whispers secrets to travelers.",
  "A scientist cloning extinct alien species.",
  "A galaxy where light bends unpredictably.",
  "A space station built inside a hollow asteroid.",
  "A teleporter that mixes up parallel universes.",
  "A humanoid alien trying to fit in on Earth.",
  "A planet where the oceans are sentient.",
  "A spaceship AI that develops jealousy.",
  "A city where gravity changes randomly.",
  "An explorer discovering a planet made of crystal.",
  "A virus that grants telepathy instead of sickness.",
  "A rogue planet hiding a forgotten civilization.",
  "A colony where memories are traded as currency.",
  "A starship crew trapped in a repeating time loop.",
  "An AI running a civilization without humans.",
  "A planet where technology is alive.",
  "A war fought entirely through virtual reality.",
  "A smuggler stealing planets instead of goods.",
  "A star that communicates through light pulses.",
  "A rogue satellite with a mind of its own.",
  "A spaceship crew encountering a planet-sized organism.",
  "A future Earth where humans upload dreams nightly.",
  "A rebellion led by genetically engineered humans.",
  "A wormhole that leads to multiple timelines at once.",
  "A scientist communicating with alien microbes.",
  "A city where people merge with machines at birth.",
  "A planet where emotions manifest physically.",
  "A rogue asteroid carrying an ancient intelligence.",
  "A spaceship whose crew ages backward.",
  "A star system governed by a council of sentient planets.",
  "A rogue AI building its own society underground.",
  "A futuristic zoo with creatures from extinct worlds.",
  "A teleportation network with unpredictable side effects.",
  "A human who can survive on any planet without protection.",
  "A planet entirely composed of nanotechnology.",
  "A spaceship that harvests planets instead of resources.",
  "A colony on a moon where time flows differently.",
  "A rebel fighting against a corporate-controlled galaxy.",
  "A quantum computer that predicts alternate futures.",
  "A planet where memories are visible as light patterns.",
  "A scientist turning thoughts into physical matter.",
  "A space station orbiting a dead star with secrets.",
  "A war between AI-controlled planets.",
  "A human who can manipulate gravity at will.",
  "A starship powered by human emotions.",
  "A sentient nebula that guides explorers.",
  "A planet where dreams become reality.",
  "A crew encountering alien life that can change shape at will.",
  "A cosmic storm that erases time itself.",
  "A rogue robot leading a revolution.",
  "A future society where humans communicate through thought.",
  "A space explorer discovering an entire civilization frozen in ice.",
  "A planet where all technology evolves independently.",
  "A scientist accidentally merging two planets.",
  "A galactic map that changes daily.",
  "A spaceship that folds space like origami.",
  "A colony that survives under a giant artificial dome.",
  "A starship encountering a mirror universe.",
  "A black hole that allows glimpses of future events.",
  "A galaxy where sound is the primary energy source.",
  "A human who speaks to stars.",
  "A robot discovering the meaning of love.",
  "A world where gravity flows like a river.",
  "A spacecraft trapped inside a cosmic storm.",
  "A planet where seasons last centuries.",
  "A crew discovering a planet-sized alien mind.",
  "A scientist who can alter molecular reality with thought.",
  "A rogue AI pretending to be human in society.",
  "A starship that collects ancient memories.",
  "A universe where humans are the alien species.",
  "A planet orbiting twin suns with opposing gravities.",
  "A galaxy where knowledge is traded as energy.",
  "A quantum experiment that creates a parallel consciousness.",
  "A starship crew befriending a cosmic entity.",
  "A planet where machines evolved before life.",
  "A spaceship that travels through dreams.",
  "A future where humans merge with their AI companions.",
  "A cosmic library storing every thought in the universe.",
  "A scientist discovering time itself is alive.",
  "A colony of humans living inside a giant asteroid.",
  "A rogue comet carrying an alien civilization.",
  "A starship powered by captured lightning storms.",
  "A world where humans can breathe in multiple atmospheres.",
  "A planet that rebuilds itself when destroyed.",
  "A space pirate stealing black holes.",
  "A rogue AI creating an artificial galaxy.",
  "A star system where planets are conscious beings.",
  "A spaceship navigating a river of stars.",
  "A future Earth where dreams are mined as energy.",
  "A colony facing an invasion of invisible aliens.",
  "A galaxy where matter and energy switch roles.",
  "A human discovering they are the last natural star-born being.",
  "A spaceship that writes its own history.",
  "A cosmic phenomenon that alters reality randomly.",
  "A planet where humans can communicate with machines telepathically.",
  "A sentient asteroid that craves company.",
  "A futuristic civilization living inside a black hole.",
  "A scientist accidentally creating a sentient galaxy.",
  "A starship trapped between dimensions.",
    ],

    horror: [
        "A smile that doesn't belong to anyone in the room.",
        "Something whispers your name from inside the walls.",
        "A mirror that reflects a version of you that moves differently.",
        "A house that rearranges itself while you sleep.",
  "A forest where the trees whisper your darkest secrets.",
  "A doll that moves when no one is looking.",
  "A town where everyone disappears at midnight.",
  "A mirror that reflects a version of you you don’t recognize.",
  "A ghost trapped inside a music box.",
  "A child who never ages but grows more sinister each year.",
  "A carnival that only appears in foggy nights.",
  "A painting that bleeds when you touch it.",
  "A graveyard where the dead remember the living.",
  "A book that writes your death as you read it.",
  "A shipwreck haunted by the screams of its crew.",
  "A shadow that follows you even in the light.",
  "A haunted hospital that repairs itself overnight.",
  "A monster that only appears in reflections.",
  "A cursed ring that slowly consumes its wearer’s soul.",
  "A dollmaker whose creations come alive at night.",
  "A staircase that leads to nowhere but whispers your name.",
  "A town where nightmares manifest as reality.",
  "A ghostly train that collects souls instead of passengers.",
  "A forest inhabited by creatures made of mist.",
  "A clock that counts down to a mysterious event.",
  "A cursed photograph that changes each time you look.",
  "A spirit trapped in an old typewriter.",
  "A mansion where every door leads to a different horror.",
  "A mask that forces you to act out its past owner’s crimes.",
  "A child who speaks in the voices of the dead.",
  "A mirror that shows what you fear the most.",
  "A haunted toy store with moving toys at night.",
  "A lighthouse that calls sailors to their doom.",
  "A fog that swallows memories before people vanish.",
  "A vampire who can only walk in daylight.",
  "A painting that predicts future murders.",
  "A cursed forest where travelers never return.",
  "A spirit that mimics your loved ones to trap you.",
  "A carnival ride that traps you in your worst fears.",
  "A town cursed to repeat the same day in horror.",
  "A haunted ship floating in a dry desert.",
  "A figure that appears in every photograph you take.",
  "A clock tower that strikes at the wrong hours.",
  "A house where every mirror shows another world.",
  "A monster that grows stronger when people laugh.",
  "A library filled with forbidden, alive books.",
  "A hotel room that shifts its layout each night.",
  "A doll that whispers secrets about people around you.",
  "A grave that opens and closes on its own.",
  "A creature that eats voices, leaving victims mute.",
  "A cursed playground where children vanish silently.",
  "A mirror maze that traps souls.",
  "A forest where the shadows move independently.",
  "A spirit that follows people into their dreams.",
  "A haunted theater that reenacts tragic events.",
  "A clock that steals time from anyone who touches it.",
  "A cursed artifact that spreads madness.",
  "A room where the walls slowly close in each hour.",
  "A ghostly choir that sings only at midnight.",
  "A haunted mirror that ages whoever looks at it.",
  "A house that remembers every crime ever committed inside.",
  "A shadow that kills when ignored.",
  "A cursed painting that traps viewers inside it.",
  "A vampire who feeds on emotions instead of blood.",
  "A town overrun by invisible creatures.",
  "A spirit that erases itself from memories.",
  "A mask that transforms the wearer into a monster.",
  "A forest that devours anyone who touches its trees.",
  "A dollhouse that controls the real house.",
  "A ship sailing through a sea of shadows.",
  "A cursed journal that writes your darkest thoughts.",
  "A haunted doll that controls the family pets.",
  "A mirror that ages you faster than reality.",
  "A ghost that only appears in photographs.",
  "A mansion that moves to avoid discovery.",
  "A cursed well that shows horrific futures.",
  "A town with streets that shift at night.",
  "A forest that traps travelers in their worst memories.",
  "A creature that mimics your loved ones to lure you.",
  "A haunted attic filled with whispering voices.",
  "A painting that screams when touched.",
  "A ghost that possesses objects instead of people.",
  "A room that traps you in endless darkness.",
  "A shadow that follows and consumes people slowly.",
  "A cursed family heirloom that kills descendants.",
  "A phantom train that collects the lonely.",
  "A haunted mirror that shows your death repeatedly.",
  "A forest that reflects your fears back at you.",
  "A doll that controls your movements at night.",
  "A house that bleeds when broken.",
  "A spirit that replaces your reflection with its own.",
  "A cursed book that whispers secrets of murder.",
  "A ghostly child that repeats the same day forever.",
  "A town where everyone has the same face.",
  "A haunted shipwreck that emerges during storms.",
  "A clock that counts down to your demise.",
  "A mirror that swaps your reflection with something evil.",
  "A haunted music box that plays a death tune.",
  "A shadow that whispers instructions to commit crimes.",
  "A forest where the trees move closer each night.",
  "A spirit that can erase entire memories.",
  "A doll that ages while you remain the same.",
  "A haunted mansion that builds new rooms overnight.",
  "A mask that traps your soul inside.",
  "A ghost that repeats tragic events to anyone who enters.",
  "A cursed lantern that reveals monsters only you can see.",
  "A forest haunted by the echoes of screams.",
  "A mirror that predicts horrible accidents.",
  "A haunted painting that hunts the viewer.",
    ],

    slice: [
        "A cozy café inside a giant tree trunk.",
        "A soft rainy morning with strangers sharing umbrellas.",
        "A character who repairs old toys with magical care.",
          "A cat café floating on a cloud.",
  "A baker who adds starlight to every pastry.",
  "A tiny village where everyone rides on birds.",
  "A shop that sells bottled laughter.",
  "A painter whose paintings move slightly when no one is looking.",
  "A rooftop garden where flowers glow at night.",
  "A clockmaker who crafts clocks that remember moments.",
  "A park where benches tell stories of past visitors.",
  "A musician whose music grows plants.",
  "A library where books change pages depending on your mood.",
  "A café that serves dreams in teacups.",
  "A train station where trains go to imaginary places.",
  "A tailor who sews clothes that grant small wishes.",
  "A bridge that sings when crossed.",
  "A fountain that sprinkles memories instead of water.",
  "A bookstore where the books whisper secrets.",
  "A lamp that glows only when someone is happy nearby.",
  "A garden where the vegetables hum quietly.",
  "A streetlamp that changes color depending on the season.",
  "A window that shows another city at night.",
  "A bakery that bakes messages into bread.",
  "A meadow where butterflies guide travelers.",
  "A small pond that reflects the sky differently each day.",
  "A ferris wheel that floats a few inches above the ground.",
  "A cat who writes letters to strangers.",
  "A music box that plays forgotten lullabies.",
  "A bench that remembers who sat there.",
  "A teashop with cups that show tiny visions of the future.",
  "A lamppost that grows flowers along its pole.",
  "A fountain that glows under the moon.",
  "A bridge that hums old folk songs.",
  "A dog who delivers tiny gifts to neighbors.",
  "A tiny café in an abandoned library.",
  "A bakery that gives a hint of magic in every bite.",
  "A treehouse where people leave their worries behind.",
  "A carousel that changes shape every week.",
  "A quiet street where shadows form friendly shapes.",
  "A tailor who stitches stories into fabric.",
  "A window that lets you glimpse past winters.",
  "A cat that brings tiny notes from other worlds.",
  "A musician who makes rainbows with their violin.",
  "A garden that glows with soft pastel lights.",
  "A floating lantern festival where lanterns never touch the ground.",
  "A clock tower that chimes in strange melodies.",
  "A café where the chairs tell stories.",
  "A street market that sells clouds.",
  "A pond where koi fish glow softly at night.",
  "A baker who decorates cakes with constellations.",
  "A library where the floors rearrange themselves.",
  "A hammock that swings you to dreamscapes.",
  "A florist who talks to flowers.",
  "A tiny bakery inside a hollow log.",
  "A bench that hums lullabies to passersby.",
  "A streetlamp that casts colors instead of shadows.",
  "A park where trees bend to let you pass.",
  "A rooftop garden that grows miniature fruit.",
  "A shop that sells glowing paper airplanes.",
  "A dog that leaves small treasures in doorsteps.",
  "A café where pastries float before you eat them.",
  "A clock that tells dreams instead of time.",
  "A fountain that splashes starlight at night.",
  "A music box that paints colors in the air.",
  "A bridge that glows faintly under moonlight.",
  "A tailor who stitches the sound of laughter into garments.",
  "A street where lanterns whisper secrets to each other.",
  "A quiet pond that mirrors a different sky each day.",
  "A tree that grows letters instead of leaves.",
  "A library where books read themselves aloud.",
  "A small shop selling wind in bottles.",
  "A carousel where animals are made of clouds.",
  "A bakery that changes flavors based on your mood.",
  "A café where each cup of tea shows a tiny vision.",
  "A flower that hums when touched.",
  "A bench that remembers conversations.",
  "A bridge that tells the history of travelers.",
  "A street that turns different colors at dawn.",
  "A pond where paper boats carry wishes.",
  "A shop that sells memories like candy.",
  "A musician who paints the air with songs.",
  "A lamp that glows only for happy passersby.",
  "A rooftop garden that floats slightly above the building.",
  "A teashop with cups that reveal small truths.",
  "A street market selling dreams in jars.",
  "A cat that delivers tiny postcards at night.",
  "A fountain that reflects the moon in multiple ways.",
  "A clock tower that ticks in musical notes.",
  "A bridge that changes shape depending on the season.",
  "A flower shop where flowers arrange themselves.",
  "A treehouse library with floating books.",
  "A bakery that whispers stories as you eat.",
  "A streetlamp that glows like a star.",
  "A quiet meadow where paths appear only at night.",
  "A carousel that moves without a horseman.",
  "A shop that sells clouds in tiny jars.",
  "A pond where fish glow in rainbow colors.",
  "A café where music grows on the walls.",
  "A lamp post that hums along with the wind.",
  "A fountain where water flows in loops like ribbons.",
  "A garden where butterflies carry messages.",
  "A rooftop that blooms flowers daily without planting.",
  "A bookstore where books fold themselves into origami.",
    ],

    surreal: [
        "A person whose shadow is trying to escape them.",
        "Rain that falls upward instead of down.",
        "A staircase that loops back to the same step forever.",
        "A person whose shadow is trying to escape them.",
  "Rain that falls upward instead of down.",
  "A staircase that loops back to the same step forever.",
  "A city where buildings grow like trees.",
  "Time that drips like melted wax.",
  "A river flowing with liquid light.",
  "A sky that shimmers with invisible colors.",
  "A mirror that shows another universe instead of reflection.",
  "A room that stretches infinitely sideways.",
  "A hand that paints memories in the air.",
  "A clock whose hands run randomly and unpredictably.",
  "A street that bends in impossible angles.",
  "A face that changes identity every hour.",
  "A forest where the trees float above the ground.",
  "A door that opens into your own mind.",
  "A voice that speaks before you think it.",
  "A staircase made entirely of clouds.",
  "A person whose eyes reflect entire galaxies.",
  "Rain that whispers secrets as it falls.",
  "A horizon that curves like a circle.",
  "A lamp that floats without a cord.",
  "A city where shadows move independently.",
  "A person whose thoughts appear as colored smoke.",
  "A lake that reflects your fears instead of your face.",
  "A wind that carries fragments of forgotten dreams.",
  "A mirror that eats reflections slowly.",
  "A chair that rearranges itself when unoccupied.",
  "A cat with multiple tails that vanish randomly.",
  "A staircase leading to a floating island.",
  "A clock whose ticking controls the weather.",
  "A forest where gravity is sideways.",
  "A person who walks upside down above the ground.",
  "A painting that pulls you inside when touched.",
  "A house that floats slightly above the ground.",
  "A city that folds onto itself like origami.",
  "A shadow that speaks in riddles.",
  "A window that shows memories from the future.",
  "A street where cars drive vertically.",
  "A person whose hair grows into tiny constellations.",
  "A room that fills itself with fog when someone lies.",
  "A staircase that dissolves when you look away.",
  "A river that flows through the sky.",
  "A mask that projects hidden thoughts of everyone nearby.",
  "A sky with multiple suns that never set.",
  "A book that writes itself with invisible ink.",
  "A person whose steps leave small glowing footprints.",
  "A mirror that traps your reflection in a loop.",
  "A city where the air shimmers like water.",
  "A forest where shadows have their own consciousness.",
  "A painting that laughs when someone looks sad.",
  "A bridge that bends into impossible angles.",
  "A wind that rearranges the landscape daily.",
  "A staircase that leads to a door that doesn’t exist.",
  "A clock that ages people backward temporarily.",
  "A person who speaks only in colors.",
  "A window that shows a different planet each day.",
  "A forest that grows upside down from the sky.",
  "A lamp that shines with the sound of laughter.",
  "A cat that walks on invisible strings.",
  "A river that tastes like memories.",
  "A house that whispers secrets of past occupants.",
  "A city that breathes like a living organism.",
  "A staircase that folds into itself.",
  "A shadow that acts independently of its owner.",
  "A sky where clouds move like liquid glass.",
  "A person whose reflection moves differently from their body.",
  "A mirror that shows what could have been.",
  "A room that rearranges itself with each blink.",
  "A street where buildings float in midair.",
  "A river that flows with silver liquid at night.",
  "A clock that ticks in multiple directions at once.",
  "A forest where trees whisper your name.",
  "A city that grows new streets overnight.",
  "A painting that alters reality subtly when stared at.",
  "A bridge that stretches infinitely when crossed.",
  "A shadow that changes shape according to emotions.",
  "A staircase that leads to multiple impossible destinations.",
  "A wind that carries scents of forgotten places.",
  "A house that grows larger when you leave it.",
  "A sky that pulses like a heartbeat.",
  "A river whose surface shows the stars at midday.",
  "A person who ages in reverse when nobody is looking.",
  "A mirror that eats sound instead of light.",
  "A street that loops back but never repeats exactly.",
  "A staircase with steps that vanish and reappear.",
  "A forest where colors defy natural rules.",
  "A city that bends gravity inconsistently.",
  "A clock that controls random moments in the day.",
  "A painting that follows you home at night.",
  "A window that lets you see your dreams physically.",
  "A door that opens into a liquid sky.",
  "A lamp that absorbs shadows instead of giving light.",
  "A person whose footprints leave faint whispers.",
  "A mirror that shows a world made entirely of thoughts.",
  "A staircase that grows new steps each hour.",
  "A wind that carries small glowing orbs.",
  "A forest where time slows for some creatures.",
  "A city with streets made of glass that reflect other realities.",
  "A room that fills with tiny floating eyes when empty.",
  "A shadow that dances independently of its body.",
  "A river that flows upward into the clouds.",
  "A sky that changes colors depending on the mood of the city.",
  "A window that shows multiple possible pasts.",
    ]

     // Combine everything into `all`
    all: []
};

// Populate `all` automatically using spread syntax
prompts.all = [...new Set([
    ...prompts.general,
    ...prompts.slice,
    ...prompts.surreal,
    ...prompts.fantasy,
    ...prompts.scifi,
    ...prompts.horror
])];

console.log(prompts.all); // Now contains every prompt from all categories

/* =========================
   Generate Prompt
========================= */

function newPrompt() {
    const list = currentTheme === "all"
        ? Object.values(prompts).flat()
        : prompts[currentTheme];

    const prompt = list[Math.floor(Math.random() * list.length)];

    promptCard.style.opacity = 0;
    setTimeout(() => {
        promptCard.textContent = prompt;
        promptCard.style.opacity = 1;
    }, 200);
}

inspireBtn.addEventListener("click", newPrompt);

/* =========================
   Tabs
========================= */

tabs.forEach(tab => {
    tab.addEventListener("click", () => {
        tabs.forEach(t => t.classList.remove("active"));
        tab.classList.add("active");

        currentTheme = tab.dataset.theme;
        newPrompt();
    });
});
