export const surrealPrompts = [
        "A person whose shadow is trying to escape them.",
        "Rain that falls upward instead of down.",
        "A staircase that loops back to the same step forever.",
        "A person whose shadow is trying to escape them.",
  "Rain that falls upward instead of down.",
  "A staircase that loops back to the same step forever.",
  "A city where buildings grow like trees.",
  "Time that drips like melted wax.",
  "A river flowing with liquid light.",
  "A sky that shimmers with invisible colors.",
  "A mirror that shows another universe instead of reflection.",
  "A room that stretches infinitely sideways.",
  "A hand that paints memories in the air.",
  "A clock whose hands run randomly and unpredictably.",
  "A street that bends in impossible angles.",
  "A face that changes identity every hour.",
  "A forest where the trees float above the ground.",
  "A door that opens into your own mind.",
  "A voice that speaks before you think it.",
  "A staircase made entirely of clouds.",
  "A person whose eyes reflect entire galaxies.",
  "Rain that whispers secrets as it falls.",
  "A horizon that curves like a circle.",
  "A lamp that floats without a cord.",
  "A city where shadows move independently.",
  "A person whose thoughts appear as colored smoke.",
  "A lake that reflects your fears instead of your face.",
  "A wind that carries fragments of forgotten dreams.",
  "A mirror that eats reflections slowly.",
  "A chair that rearranges itself when unoccupied.",
  "A cat with multiple tails that vanish randomly.",
  "A staircase leading to a floating island.",
  "A clock whose ticking controls the weather.",
  "A forest where gravity is sideways.",
  "A person who walks upside down above the ground.",
  "A painting that pulls you inside when touched.",
  "A house that floats slightly above the ground.",
  "A city that folds onto itself like origami.",
  "A shadow that speaks in riddles.",
  "A window that shows memories from the future.",
  "A street where cars drive vertically.",
  "A person whose hair grows into tiny constellations.",
  "A room that fills itself with fog when someone lies.",
  "A staircase that dissolves when you look away.",
  "A river that flows through the sky.",
  "A mask that projects hidden thoughts of everyone nearby.",
  "A sky with multiple suns that never set.",
  "A book that writes itself with invisible ink.",
  "A person whose steps leave small glowing footprints.",
  "A mirror that traps your reflection in a loop.",
  "A city where the air shimmers like water.",
  "A forest where shadows have their own consciousness.",
  "A painting that laughs when someone looks sad.",
  "A bridge that bends into impossible angles.",
  "A wind that rearranges the landscape daily.",
  "A staircase that leads to a door that doesn’t exist.",
  "A clock that ages people backward temporarily.",
  "A person who speaks only in colors.",
  "A window that shows a different planet each day.",
  "A forest that grows upside down from the sky.",
  "A lamp that shines with the sound of laughter.",
  "A cat that walks on invisible strings.",
  "A river that tastes like memories.",
  "A house that whispers secrets of past occupants.",
  "A city that breathes like a living organism.",
  "A staircase that folds into itself.",
  "A shadow that acts independently of its owner.",
  "A sky where clouds move like liquid glass.",
  "A person whose reflection moves differently from their body.",
  "A mirror that shows what could have been.",
  "A room that rearranges itself with each blink.",
  "A street where buildings float in midair.",
  "A river that flows with silver liquid at night.",
  "A clock that ticks in multiple directions at once.",
  "A forest where trees whisper your name.",
  "A city that grows new streets overnight.",
  "A painting that alters reality subtly when stared at.",
  "A bridge that stretches infinitely when crossed.",
  "A shadow that changes shape according to emotions.",
  "A staircase that leads to multiple impossible destinations.",
  "A wind that carries scents of forgotten places.",
  "A house that grows larger when you leave it.",
  "A sky that pulses like a heartbeat.",
  "A river whose surface shows the stars at midday.",
  "A person who ages in reverse when nobody is looking.",
  "A mirror that eats sound instead of light.",
  "A street that loops back but never repeats exactly.",
  "A staircase with steps that vanish and reappear.",
  "A forest where colors defy natural rules.",
  "A city that bends gravity inconsistently.",
  "A clock that controls random moments in the day.",
  "A painting that follows you home at night.",
  "A window that lets you see your dreams physically.",
  "A door that opens into a liquid sky.",
  "A lamp that absorbs shadows instead of giving light.",
  "A person whose footprints leave faint whispers.",
  "A mirror that shows a world made entirely of thoughts.",
  "A staircase that grows new steps each hour.",
  "A wind that carries small glowing orbs.",
  "A forest where time slows for some creatures.",
  "A city with streets made of glass that reflect other realities.",
  "A room that fills with tiny floating eyes when empty.",
  "A shadow that dances independently of its body.",
  "A river that flows upward into the clouds.",
  "A sky that changes colors depending on the mood of the city.",
  "A window that shows multiple possible pasts.",
    ];