export const fantasyPrompts = [
        "A wizard who writes spells on floating paper charms.",
        "A forest that only appears when someone is lost.",
        "A knight whose armor is made of living vines.",
        "A mage who bottles starlight to heal others.",
        "A castle that drifts through the clouds like a ship.",
        "A dragon that hoards forgotten childhood memories.",
        "A librarian who guards books that rewrite themselves.",
        "A knight made of broken stained-glass pieces.",
        "A forest where shadows whisper prophecies.",
        "A traveler who speaks the language of storms.",
        "A potion brewer who harvests ingredients from dreams.",
        "A kingdom ruled by a council of enchanted masks.",
        "A fairy who tries to impersonate a human but gets everything slightly wrong.",
        "A river that flows backward to a lost era.",
        "A warrior who befriended the monster they were sent to slay.",
  "A phoenix nurtured by music instead of fire.",
  "A sentient sword that doubts its destiny.",
  "A witch whose familiar keeps trying to run the coven.",
  "A town that celebrates “Opposite Day” using real reality-bending magic.",
  "A royal family descended from sea serpents.",
  "A wandering healer who carries magic in their tattoos.",
  "A centaur scholar building a magical observatory.",
  "A herb garden tended by tiny elemental spirits.",
  "A mountain that shifts its paths to test travelers.",
  "A village protected by a polite but terrifying forest spirit.",
  "A bard whose music forces emotions into physical form.",
  "A ghost knight who guards a ruined bridge.",
  "A relic that grants power but slowly becomes alive.",
  "A dragon disguised as a common house pet.",
  "A kingdom built atop a sleeping giant.",
  "A sorcerer who bargains with the moon.",
  "A shapeshifter trying to live an ordinary life.",
  "A wizard who can only cast spells by writing poems.",
  "A legendary beast that appears only during snowstorms.",
  "A magical bakery that grants wishes through pastries.",
  "A forest where fallen leaves transform into tiny sprites.",
  "A cursed well that shows too many possible futures.",
  "A warrior chosen by a celestial fox.",
  "A haunted harp that plays itself on stormy nights.",
  "A mage academy built inside a colossal shell.",
  "A dragon slayer and dragon forced to team up.",
  "A village where everyone is born with a small magical flaw.",
  "A prophet who only hears omens through animals.",
  "A lantern that contains a fragment of the sun.",
  "A mage trying to resurrect a lost mythical species.",
  "An enchanted book that refuses to open for anyone arrogant.",
  "A giant who collects tiny enchanted trinkets.",
  "An ancient spirit living inside a paintbrush.",
  "A unicorn that refuses to be found.",
  "A guardian spirit trapped in a pocket watch.",
  "A crystal cavern that echoes memories.",
  "A witch who brews potions from forgotten songs.",
  "A stone golem who wants to become human.",
  "A fountain that blesses travelers but takes a memory as payment.",
  "A forest protected by living vines that choose who may pass.",
  "A hero cursed to speak only in riddles.",
  "A merfolk trader dealing in dangerous curiosities.",
  "A dragon egg about to hatch in an unexpected place.",
  "A sentient cloak with a mischievous personality.",
  "A forgotten god awakening after centuries of silence.",
  "A wizard who accidentally turns emotions into weather.",
  "A fairy ring that opens only when no one is looking.",
  "A magical animal companion going on its own adventure.",
  "A warrior who forges weapons from their dreams.",
  "A wandering knight seeking a worthy cause.",
  "A spellworker who steals bad memories.",
  "A city built inside a floating crystal monolith.",
  "A healer who extracts curses like splinters.",
  "A grumpy dragon babysitting magical creatures.",
  "A mage who weaves powerful illusions using glass threads.",
  "A kingdom defended by sentient guardian statues.",
  "A magical storm that erases lies.",
  "A potion that reveals hidden truth — wanted by everyone.",
  "A hermit wizard living inside a giant mushroom.",
  "A knight who rides a phantom horse.",
  "A hidden marketplace that appears only at dawn.",
  "A young mage forced to tame a wild spell.",
  "A creature that repeats everything you say… but wrong.",
  "A fae trickster trying to earn redemption.",
  "A castle that keeps remodeling itself.",
  "A spirit trapped inside a music box.",
  "A cursed tapestry that slowly comes alive.",
  "A witch who commands flowers instead of flames.",
  "A kingdom where everyone has feathers instead of hair.",
  "A river spirit guiding lost travelers.",
  "A legendary sword waiting for its rightful wielder.",
  "A mage who accidentally gave life to their shadow.",
  "A ghost fox haunting an abandoned shrine.",
  "A witch casting spells using embroidered patterns.",
  "A magical pet causing too much trouble.",
  "A knight competing in a mystical tournament.",
  "A world where constellations fall to earth.",
  "A traveler collecting relics from extinct magical species.",
  "A divine messenger disguised as a street performer.",
  "A magical bond forming between strangers.",
  "A hero confronting a benevolent monster.",
  "A corrupted forest yearning to be healed.",
  "A magical creature guarding a forgotten child.",
  "A mage who manipulates time using sand.",
  "A fae creature hiding from its own kind.",
  "A city built atop a slumbering dragon.",
  "A witch who commands wooden puppets.",
  "A young hero guided by a mysterious glowing creature.",
    ];