export const sciFiPrompts = [
        "A robot learning to dream for the first time.",
        "A city powered by bottled thunderstorms.",
        "A spaceship grown like a living organism.",
        "A spaceship that harvests stars for fuel.",
  "An AI that dreams of becoming human.",
  "A planet where time moves backward every other day.",
  "A rogue astronaut communicating with a parallel Earth.",
  "A city floating above a toxic ocean.",
  "A scientist who can transfer consciousness into machines.",
  "A robot detective investigating its own crimes.",
  "A starship that vanishes into other dimensions.",
  "A colony on Mars struggling with mysterious illnesses.",
  "A hologram that starts gaining real memories.",
  "A civilization powered entirely by musical vibrations.",
  "A black hole that whispers secrets to travelers.",
  "A scientist cloning extinct alien species.",
  "A galaxy where light bends unpredictably.",
  "A space station built inside a hollow asteroid.",
  "A teleporter that mixes up parallel universes.",
  "A humanoid alien trying to fit in on Earth.",
  "A planet where the oceans are sentient.",
  "A spaceship AI that develops jealousy.",
  "A city where gravity changes randomly.",
  "An explorer discovering a planet made of crystal.",
  "A virus that grants telepathy instead of sickness.",
  "A rogue planet hiding a forgotten civilization.",
  "A colony where memories are traded as currency.",
  "A starship crew trapped in a repeating time loop.",
  "An AI running a civilization without humans.",
  "A planet where technology is alive.",
  "A war fought entirely through virtual reality.",
  "A smuggler stealing planets instead of goods.",
  "A star that communicates through light pulses.",
  "A rogue satellite with a mind of its own.",
  "A spaceship crew encountering a planet-sized organism.",
  "A future Earth where humans upload dreams nightly.",
  "A rebellion led by genetically engineered humans.",
  "A wormhole that leads to multiple timelines at once.",
  "A scientist communicating with alien microbes.",
  "A city where people merge with machines at birth.",
  "A planet where emotions manifest physically.",
  "A rogue asteroid carrying an ancient intelligence.",
  "A spaceship whose crew ages backward.",
  "A star system governed by a council of sentient planets.",
  "A rogue AI building its own society underground.",
  "A futuristic zoo with creatures from extinct worlds.",
  "A teleportation network with unpredictable side effects.",
  "A human who can survive on any planet without protection.",
  "A planet entirely composed of nanotechnology.",
  "A spaceship that harvests planets instead of resources.",
  "A colony on a moon where time flows differently.",
  "A rebel fighting against a corporate-controlled galaxy.",
  "A quantum computer that predicts alternate futures.",
  "A planet where memories are visible as light patterns.",
  "A scientist turning thoughts into physical matter.",
  "A space station orbiting a dead star with secrets.",
  "A war between AI-controlled planets.",
  "A human who can manipulate gravity at will.",
  "A starship powered by human emotions.",
  "A sentient nebula that guides explorers.",
  "A planet where dreams become reality.",
  "A crew encountering alien life that can change shape at will.",
  "A cosmic storm that erases time itself.",
  "A rogue robot leading a revolution.",
  "A future society where humans communicate through thought.",
  "A space explorer discovering an entire civilization frozen in ice.",
  "A planet where all technology evolves independently.",
  "A scientist accidentally merging two planets.",
  "A galactic map that changes daily.",
  "A spaceship that folds space like origami.",
  "A colony that survives under a giant artificial dome.",
  "A starship encountering a mirror universe.",
  "A black hole that allows glimpses of future events.",
  "A galaxy where sound is the primary energy source.",
  "A human who speaks to stars.",
  "A robot discovering the meaning of love.",
  "A world where gravity flows like a river.",
  "A spacecraft trapped inside a cosmic storm.",
  "A planet where seasons last centuries.",
  "A crew discovering a planet-sized alien mind.",
  "A scientist who can alter molecular reality with thought.",
  "A rogue AI pretending to be human in society.",
  "A starship that collects ancient memories.",
  "A universe where humans are the alien species.",
  "A planet orbiting twin suns with opposing gravities.",
  "A galaxy where knowledge is traded as energy.",
  "A quantum experiment that creates a parallel consciousness.",
  "A starship crew befriending a cosmic entity.",
  "A planet where machines evolved before life.",
  "A spaceship that travels through dreams.",
  "A future where humans merge with their AI companions.",
  "A cosmic library storing every thought in the universe.",
  "A scientist discovering time itself is alive.",
  "A colony of humans living inside a giant asteroid.",
  "A rogue comet carrying an alien civilization.",
  "A starship powered by captured lightning storms.",
  "A world where humans can breathe in multiple atmospheres.",
  "A planet that rebuilds itself when destroyed.",
  "A space pirate stealing black holes.",
  "A rogue AI creating an artificial galaxy.",
  "A star system where planets are conscious beings.",
  "A spaceship navigating a river of stars.",
  "A future Earth where dreams are mined as energy.",
  "A colony facing an invasion of invisible aliens.",
  "A galaxy where matter and energy switch roles.",
  "A human discovering they are the last natural star-born being.",
  "A spaceship that writes its own history.",
  "A cosmic phenomenon that alters reality randomly.",
  "A planet where humans can communicate with machines telepathically.",
  "A sentient asteroid that craves company.",
  "A futuristic civilization living inside a black hole.",
  "A scientist accidentally creating a sentient galaxy.",
  "A starship trapped between dimensions.",
    ];
