export const slicePrompts = [
        "A cozy café inside a giant tree trunk.",
        "A soft rainy morning with strangers sharing umbrellas.",
        "A character who repairs old toys with magical care.",
          "A cat café floating on a cloud.",
  "A baker who adds starlight to every pastry.",
  "A tiny village where everyone rides on birds.",
  "A shop that sells bottled laughter.",
  "A painter whose paintings move slightly when no one is looking.",
  "A rooftop garden where flowers glow at night.",
  "A clockmaker who crafts clocks that remember moments.",
  "A park where benches tell stories of past visitors.",
  "A musician whose music grows plants.",
  "A library where books change pages depending on your mood.",
  "A café that serves dreams in teacups.",
  "A train station where trains go to imaginary places.",
  "A tailor who sews clothes that grant small wishes.",
  "A bridge that sings when crossed.",
  "A fountain that sprinkles memories instead of water.",
  "A bookstore where the books whisper secrets.",
  "A lamp that glows only when someone is happy nearby.",
  "A garden where the vegetables hum quietly.",
  "A streetlamp that changes color depending on the season.",
  "A window that shows another city at night.",
  "A bakery that bakes messages into bread.",
  "A meadow where butterflies guide travelers.",
  "A small pond that reflects the sky differently each day.",
  "A ferris wheel that floats a few inches above the ground.",
  "A cat who writes letters to strangers.",
  "A music box that plays forgotten lullabies.",
  "A bench that remembers who sat there.",
  "A teashop with cups that show tiny visions of the future.",
  "A lamppost that grows flowers along its pole.",
  "A fountain that glows under the moon.",
  "A bridge that hums old folk songs.",
  "A dog who delivers tiny gifts to neighbors.",
  "A tiny café in an abandoned library.",
  "A bakery that gives a hint of magic in every bite.",
  "A treehouse where people leave their worries behind.",
  "A carousel that changes shape every week.",
  "A quiet street where shadows form friendly shapes.",
  "A tailor who stitches stories into fabric.",
  "A window that lets you glimpse past winters.",
  "A cat that brings tiny notes from other worlds.",
  "A musician who makes rainbows with their violin.",
  "A garden that glows with soft pastel lights.",
  "A floating lantern festival where lanterns never touch the ground.",
  "A clock tower that chimes in strange melodies.",
  "A café where the chairs tell stories.",
  "A street market that sells clouds.",
  "A pond where koi fish glow softly at night.",
  "A baker who decorates cakes with constellations.",
  "A library where the floors rearrange themselves.",
  "A hammock that swings you to dreamscapes.",
  "A florist who talks to flowers.",
  "A tiny bakery inside a hollow log.",
  "A bench that hums lullabies to passersby.",
  "A streetlamp that casts colors instead of shadows.",
  "A park where trees bend to let you pass.",
  "A rooftop garden that grows miniature fruit.",
  "A shop that sells glowing paper airplanes.",
  "A dog that leaves small treasures in doorsteps.",
  "A café where pastries float before you eat them.",
  "A clock that tells dreams instead of time.",
  "A fountain that splashes starlight at night.",
  "A music box that paints colors in the air.",
  "A bridge that glows faintly under moonlight.",
  "A tailor who stitches the sound of laughter into garments.",
  "A street where lanterns whisper secrets to each other.",
  "A quiet pond that mirrors a different sky each day.",
  "A tree that grows letters instead of leaves.",
  "A library where books read themselves aloud.",
  "A small shop selling wind in bottles.",
  "A carousel where animals are made of clouds.",
  "A bakery that changes flavors based on your mood.",
  "A café where each cup of tea shows a tiny vision.",
  "A flower that hums when touched.",
  "A bench that remembers conversations.",
  "A bridge that tells the history of travelers.",
  "A street that turns different colors at dawn.",
  "A pond where paper boats carry wishes.",
  "A shop that sells memories like candy.",
  "A musician who paints the air with songs.",
  "A lamp that glows only for happy passersby.",
  "A rooftop garden that floats slightly above the building.",
  "A teashop with cups that reveal small truths.",
  "A street market selling dreams in jars.",
  "A cat that delivers tiny postcards at night.",
  "A fountain that reflects the moon in multiple ways.",
  "A clock tower that ticks in musical notes.",
  "A bridge that changes shape depending on the season.",
  "A flower shop where flowers arrange themselves.",
  "A treehouse library with floating books.",
  "A bakery that whispers stories as you eat.",
  "A streetlamp that glows like a star.",
  "A quiet meadow where paths appear only at night.",
  "A carousel that moves without a horseman.",
  "A shop that sells clouds in tiny jars.",
  "A pond where fish glow in rainbow colors.",
  "A café where music grows on the walls.",
  "A lamp post that hums along with the wind.",
  "A fountain where water flows in loops like ribbons.",
  "A garden where butterflies carry messages.",
  "A rooftop that blooms flowers daily without planting.",
  "A bookstore where books fold themselves into origami.",
    ];